category_list_banners:
  type: list
  default: "1;#9A56A2;Heading 1|4;#3271B4;Heading 2"
  description:
    en: 'Semicolon delimited in this order: Tag name;Color;Description<br>The description will only be shown on tag banners'
